name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: installing lcov
        run: sudo apt install lcov

      - name: install gtest
        run: sudo apt install libgtest-dev

      - name: build-project
        run: make build

      - name: running test
        run: make run-tests

  valgrind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install gtest
        run: sudo apt install libgtest-dev

      - name: update
        run: sudo apt-get update

      - name: install valgrind
        run: sudo apt-get install valgrind

      - name: build
        run: cmake -Dtest=true -B ./build

      - name: make
        run: cmake --build ./build

      - name: run-gtests
        run: make run-valgrind